sudo: required
services:
    - docker

before_install:
    - docker build -t tzeeka/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true tzeeka/react-test npm test

after_success:
    - docker build -t tzeeka/multi-client ./client
    - docker build -t tzeeka/multi-nginx ./nginx
    - docker build -t tzeeka/multi-server ./server
    - docker build -t tzeeka/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push tzeeka/multi-client
    - docker push tzeeka/multi-nginx 
    - docker push tzeeka/multi-server 
    - docker push tzeeka/multi-worker
    
deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-1-935494081658
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY